apiVersion: skaffold/v4beta11
kind: Config
build:
  local: # build locally
    push: false # don't push to a registry (default)
  artifacts:
    - image: haryati75/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: haryati75/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: haryati75/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: haryati75/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: haryati75/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: haryati75/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*

portForward:
  - resourceType: service
    resourceName: auth-mongo-srv
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: tickets-mongo-srv
    port: 27017
    localPort: 27018
  - resourceType: service
    resourceName: orders-mongo-srv
    port: 27017
    localPort: 27019
  - resourceType: service
    resourceName: payments-mongo-srv
    port: 27017
    localPort: 27020
